In [1]:
import numpy as np 
import tensorflow as tf 
import torch

2024-02-09 16:06:08.412369: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-02-09 16:06:08.412435: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-02-09 16:06:08.449471: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-02-09 16:06:08.533889: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-02-09 16:06:10.053816: W tensorflow/compiler/tf2

In [2]:
print(torch.__version__)

2.2.0+cu121


In [3]:
print(tf.__version__)

2.15.0


### Orthagonal Vector

In [2]:
import numpy as np

In [3]:
i = np.array([1,0])
j = np.array([0,1])

In [4]:
np.dot(i, j)

0

In [6]:
x = np.array([[1,2,3], [4,5,6], [7,8,9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
x.shape

(3, 3)

In [9]:
x.size

9

In [11]:
x[:, 0]

array([1, 4, 7])

In [12]:
x[1, :]

array([4, 5, 6])

In [13]:
x[0:2, 0:2]

array([[1, 2],
       [4, 5]])

### Matrix in Pytorch

In [16]:
import torch
x = torch.tensor([[1,2,3], [4,5,6], [7,8,9]])
x

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [17]:
x.shape

torch.Size([3, 3])

In [18]:
x.size()

torch.Size([3, 3])

In [19]:
x[:, 0]

tensor([1, 4, 7])

In [20]:
x[0, :]

tensor([1, 2, 3])

### Matrix in Tensorflow

In [22]:
import tensorflow as tf 

2024-02-09 17:12:41.096342: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-02-09 17:12:41.096406: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-02-09 17:12:41.134295: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-02-09 17:12:41.225157: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-02-09 17:12:42.962826: W tensorflow/compiler/tf2

In [23]:
tf

<module 'tensorflow' from '/home/nishant/anaconda3/lib/python3.11/site-packages/tensorflow/__init__.py'>

In [24]:
x = tf.Variable([[1,2,3], [4,5,6], [7,8,9]])

In [25]:
x

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [26]:
x.numpy()

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)

In [28]:
tf.rank(x).numpy()

2

In [33]:
tf.shape(x)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 3], dtype=int32)>

In [34]:
x.shape

TensorShape([3, 3])

In [35]:
tf.size(x)

<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [38]:
x[:, 0]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 4, 7], dtype=int32)>

In [39]:
x[0, :]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [40]:
x

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [42]:
image_point = torch.zeros([32, 28, 28, 3])
image_point

tensor([[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         ...,

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0.

In [43]:
image_point = tf.zeros([32, 28, 28, 3])
image_point

<tf.Tensor: shape=(32, 28, 28, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        ...,

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


   