# Welcome to Numpy Tutorial 

*this*

**this**

***this***

In [1]:
#Reference
# Numpy Type Reference
# Numpy Documentation
# Array creation Method in numpy    #https://docs.scipy.org/doc/numpy-1.10.1/user/basics.creation.html


In [4]:
import numpy as np

In [3]:
#myarr = np.array([3,6,37777778777,7], np.int8)   #Overflow Error
myarr = np.array([3,6,37,7], np.int8)   #creation of numpy array of int8 type

In [4]:
myarr

array([ 3,  6, 37,  7], dtype=int8)

In [5]:
myarr

array([ 3,  6, 37,  7], dtype=int8)

In [6]:
myarr2 = np.array([4,5,7,8])

In [7]:
myarr2[1]

5

In [8]:
myarr3 = np.array([[3,5,6,7]])

In [9]:
myarr3[0,3]

7

In [10]:
myarr3.shape  #give shapes as (1,4) 1 means only one row and 4 means only 4 columns

(1, 4)

In [11]:
myarr3.dtype

dtype('int32')

In [12]:
myarr3

array([[3, 5, 6, 7]])

In [13]:
myarr3[0,1] = 34

In [14]:
myarr3

array([[ 3, 34,  6,  7]])

In [15]:
myarr4 = np.array([(4,5,67,23)])

In [16]:
myarr4

array([[ 4,  5, 67, 23]])

In [17]:
myarr4[0,2]

67

In [18]:
myarr4.dtype

dtype('int32')

# Array Creation  :-  Conversion from other Python structures (e.g., lists, tuples)

In [19]:
listarray = np.array([[1,2,3], [5,8,5], [0,3,1]])

In [20]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [21]:
listarray.dtype

dtype('int32')

In [22]:
listarray.shape

(3, 3)

In [23]:
listarray.size

9

In [24]:
listarray[1,2]

5

In [25]:
arr = np.array({34,23, 78, 99})   #dtype becomes by default object by using set and 'dtype- object is not efficient so use int or float array

In [26]:
arr

array({34, 99, 78, 23}, dtype=object)

# Array Creation :-Intrinsic numpy array array creation objects

In [27]:
zeros = np.zeros((2,5))

In [28]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [29]:
zeros.dtype

dtype('float64')

In [30]:
zeros.shape

(2, 5)

In [31]:
zeros.size

10

In [32]:
rng = np.arange(15) # create an array from 0 to (15-1) elements

In [33]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [34]:
lspace = np.linspace(1,10,8)

In [35]:
lspace

array([ 1.        ,  2.28571429,  3.57142857,  4.85714286,  6.14285714,
        7.42857143,  8.71428571, 10.        ])

In [36]:
emp = np.empty((4,6))  #create (4,6) empty array and all elements will be random

In [37]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.69119873e-306, 1.78020848e-306, 8.90095411e-307],
       [1.78021798e-306, 6.23053614e-307, 2.22526399e-307,
        6.23053614e-307, 7.56592338e-307, 1.60216183e-306],
       [7.56602523e-307, 3.56043054e-307, 1.37961641e-306,
        2.22518251e-306, 1.33511969e-306, 6.23037317e-307],
       [6.23053954e-307, 9.34609790e-307, 8.45593934e-307,
        9.34600963e-307, 1.86921143e-306, 6.23061763e-307]])

In [38]:
emp_like = np.empty_like(lspace)  # create a new copied empty array. we use it for efficiency

In [39]:
emp_like

array([ 1.        ,  2.28571429,  3.57142857,  4.85714286,  6.14285714,
        7.42857143,  8.71428571, 10.        ])

In [40]:
ide = np.identity(45) # creates an identity matrix of (45,45)

In [41]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [42]:
ide.shape

(45, 45)

In [43]:
ide.size

2025

In [44]:
arr = np.arange(99)

In [45]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [46]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [47]:
arr.reshape(3,31) # throw an error

ValueError: cannot reshape array of size 99 into shape (3,31)

In [48]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [49]:
arr = arr.reshape(3,33)

In [50]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [51]:
arr = arr.ravel()  # makes our array to be straight means create 1-D array

In [52]:
arr.shape

(99,)

# Axis Array

In [1]:
x = [[1,2,3], [4,5,6], [7,1,0]]

In [5]:
arr = np.array(x)

In [6]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [7]:
arr.sum(axis = 0)

array([12,  8,  9])

In [8]:
arr.sum(axis = 1)

array([ 6, 15,  8])

In [11]:
#Numpty attributes and methods
arr.T    # Trasnpose of the array

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [13]:
arr.flat  # gives an iterator

In [14]:
for item in arr.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [15]:
arr.ndim #gives number of dimension

2

In [16]:
arr.size

9

In [18]:
arr.nbytes  # gives total bytes consumed in the memory by all elements

36

In [28]:
one = np.array([1,3,4,634,2])

In [29]:
one.argmax() # gives the index of maximum valued element

3

In [30]:
one.argmin() # gives the index of minimum valued element

0

In [31]:
one

array([  1,   3,   4, 634,   2])

In [33]:
one.argsort()  #give the array of index in such a manner that if i put my elment according to these index my array will got sorted 

array([0, 4, 1, 2, 3], dtype=int64)

In [36]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [38]:
arr.argmin()

8

In [40]:
arr.argmax()

6

In [41]:
arr.argmax(axis = 0)

array([2, 1, 1], dtype=int64)

In [42]:
arr.argmax(axis = 1)

array([2, 2, 0], dtype=int64)

In [43]:
arr.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [46]:
arr.argsort(axis = 0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [47]:
arr.argsort(axis = 1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [48]:
arr.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [51]:
arr.reshape((9,))

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [52]:
arr.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [54]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [55]:
arr2 = np.array([[1,2,1],
                 [4,0,6],
                 [8,1,0]])

In [56]:
arr + arr2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [57]:
arr - arr2

array([[ 0,  0,  2],
       [ 0,  5,  0],
       [-1,  0,  0]])

In [59]:
[4,6] + [23,66]  # only extends the list but cannot do operation like in matrix 

[4, 6, 23, 66]

In [60]:
arr * arr2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [63]:
np.sqrt(arr) # do the square root of every elemnent of the array

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [64]:
arr.sum()

29

In [65]:
arr.max()

7

In [66]:
arr.min()

0

In [67]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [70]:
np.where(arr > 5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [71]:
type(np.where(arr > 5))

tuple

In [73]:
np.count_nonzero(arr)  # gives the total number of non-zero elements of the array

8

In [77]:
np.nonzero(arr)   # gives the non zero index of array so these are (0,0), (0,1), (0,2), (1,0), (1,1) .... (2,1) 
                #gives the tuple for every axis 

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1], dtype=int64))

In [78]:
arr[1,2] = 0

In [79]:
np.nonzero(arr)

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1], dtype=int64))

In [80]:
import sys 

In [81]:
py_ar = [0, 4, 55,2]

In [82]:
np_ar = np.array(py_ar)

In [84]:
sys.getsizeof(1) * len(py_ar)  # get size of 1 element and multiply by length of python array

112

In [91]:
np_ar.itemsize   # gives the size of one element of the array in the memory 

4

In [92]:
np_ar.itemsize * np_ar.size

16

In [93]:
np_ar.tolist() # converts numpy array to python list 

[0, 4, 55, 2]

*for more  reference search  "numpy array methods and attributes" go to "https://docs.scipy.org/doc//numpy-1.10.4/reference/arrays.html"*