In [2]:
import numpy as np

In [26]:
arr = np.array([23,4,56])
print(arr.dtype)

int32


In [57]:
arr = np.array([23.234,67.234,69.34])
print(arr)
arr = arr.astype('i')
print(arr)
arr = arr.astype('b')
print(arr)
print(arr.dtype)

[23.234 67.234 69.34 ]
[23 67 69]
[23 67 69]
int8


In [80]:
arr = np.array([12.56,67.234,69.34, 0], dtype = 'i')
print(arr)
new_arr = arr.astype(bool)
print(new_arr)
print(arr.dtype)

[12 67 69  0]
[ True  True  True False]
int32


In [91]:
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.base)
new_arr = arr.view()
new_arr[2] = 100
print(arr)
print(new_arr)
print(arr.base)
print(new_arr.base)

[1 2 3 4 5]
None
[  1   2 100   4   5]
[  1   2 100   4   5]
None
[  1   2 100   4   5]


In [98]:
arr = np.array([[[1,2,3,4,5,6], [11,12,13,14,15,16]]])
print(arr.size)
print(arr.shape) # No. of element in each dimension

12
(1, 2, 6)


In [101]:
arr = np.array([1,2,3,5], ndmin = 5)
print(arr)

[[[[[1 2 3 5]]]]]


In [103]:
print(arr[0])

[[[[1 2 3 5]]]]


In [110]:
print(arr[0][0])
print(arr[0,0,0,0])
print(arr.shape)

[[[1 2 3 5]]]
[1 2 3 5]
(1, 1, 1, 1, 4)


In [147]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)
print(arr.ndim)
print("Done")
new_arr = arr.reshape(2,2,-1)
print(new_arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
Done
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [158]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
# for x in arr:
#     for y in x:
#         for z in y:
#             print(z)

for x in np.nditer(arr):
    print(x, end = "  ")

1  2  3  4  5  6  7  8  9  10  11  12  

In [162]:
arr = np.arange(12).reshape(3,4)
print(arr)
for x in np.nditer(arr):
    print(x, end="  ")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
0  1  2  3  4  5  6  7  8  9  10  11  

In [172]:
arr = np.arange(24).reshape(4,6)
print(arr)
print("Done")
for x in np.nditer(arr[0:2, 2:5:2]):
    print(x, end = "  ")

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
Done
2  4  8  10  

In [177]:
arr = np.arange(24).reshape(24)
print(arr)
print("Done")
for index, x in np.ndenumerate(arr[2:6:2]):
    print(index, x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
Done
(0,) 2
(1,) 4


In [196]:
arr1 = np.array([1,2,3,4,5,6]).reshape(2,3)
arr2 = np.array([11,12,13,14,15,16]).reshape(2,3)
print(arr1)
print(arr2)
print("Done")
# arr = np.stack((arr1, arr2),axis = 1)
arr = np.dstack((arr1 ,arr2))
print(arr)

[[1 2 3]
 [4 5 6]]
[[11 12 13]
 [14 15 16]]
Done
[[[ 1 11]
  [ 2 12]
  [ 3 13]]

 [[ 4 14]
  [ 5 15]
  [ 6 16]]]
